# Generated by Django 2.2.14 on 2023-03-15 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='badge',
            field=models.CharField(blank=True, choices=[('New', 'New')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('C', 'Canon'), ('S', 'Sony'), ('N', 'Nikon'), ('F', 'Fujifilm'), ('P', 'Panasonic'), ('O', 'Olympus'), ('PX', 'Pentax'), ('IN', 'Instax')], default='C', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='descriptionFo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_key',
            field=models.CharField(default='default key', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'camera'), ('TP', 'tripods'), ('FL', 'flashlights'), ('MC', 'memoryCards'), ('CB', 'cameraBags'), ('B', 'batteries')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='core.OrderItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Item'),
        ),
    ]
